name: CI/CD Pipeline

on:
  push:
    branches: [main, temp]
  pull_request:
    branches: [main, temp]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies with no caches
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test -- --coverage
        env:
          CI: true

      - name: Check test coverage
        run: |
          COVERAGE=$(npx vitest run --coverage | grep "All files" | awk '{print $4}' | sed 's/%//g')
          # todo 6% to 60%
          if (( $(echo "$COVERAGE < 6" | bc -l) )); then
            echo "Test coverage is below 6%. Current coverage: $COVERAGE%"
            exit 1
          else
            echo "Test coverage is above 6%. Current coverage: $COVERAGE%"
          fi

      - name: Build project
        run: npm run build

      - name: Package Extension
        run: |
          cd dist
          zip -r ../extension.zip .

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            coverage/
            test-results/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-package
          path: |
            dist/
            extension.zip 